openapi: 3.0.3
info:
  title: WebApplication3
  version: '1.0'
paths:
  '/weatherforecast/{id}':
    post:
      tags:
        - WebApplication3
      operationId: GetWeatherForecast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: language
          in: header
          schema:
            type: string
            default: de-DE
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherResponse'
components:
  schemas:
    MyEnum:
      enum:
        - VALUE
        - NO_VALUE
        - MULT_IVALUE
      type: string
    MyItem:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          description: A required Id.
          format: int32
          example: 12312512
        someNullableId:
          type: integer
          description: This id is nullable.
          format: int32
          nullable: true
      additionalProperties: false
      description: A Single Element representing some data.
    RequestBody:
      required:
        - dateTime
      type: object
      properties:
        dateTime:
          type: string
          description: Some DateTime filter. Is required.
          format: date-time
        indicator:
          $ref: '#/components/schemas/MyEnum'
      additionalProperties: false
      description: The request body summary.
    WeatherResponse:
      type: object
      properties:
        freeformObjectType1:
          type: object
          additionalProperties: true
        freeformObjectType2:
          type: object
          additionalProperties: {}
        a1:
          type: object
          additionalProperties:
            type: boolean
        a2:
          type: object
          additionalProperties:
            type: integer
            format: int32
        a3:
          type: object
          additionalProperties:
            type: array
            items:
              type: integer
              format: int32
        a4:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MyEnum'
        a5:
          type: array
          items:
            type: object
            additionalProperties:
              type: object
              additionalProperties:
                type: string
        a6:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MyItem'
      additionalProperties: false
      description: The WeatherForecast element. Represents one day.